name: scp copy folder to remote via SSH

on:
  push
jobs:    
      
  uses: appleboy/scp-action@master
  with:
    host: ${{ secrets.HOST }}
    username: ${{ secrets.USERNAME }}
    port: ${{ secrets.PORT }}
    key: ${{ secrets.KEY }}
    source: "home/rabi/test.xml"
    target: "home/rabi"