name: Java CI

on: [push]

      name: copy file via ssh key
      runs-on: ubuntu-latest
      uses: garygrossgarten/github-action-scp@release
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY }}
        source: "home/zombie/rabi/test.tar"
        target: "home/rabi"