name: Java CI

on: [push]

jobs:
  jobs1:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Mavenn
        run: mvn -B package --file pom.xml
  jobs2:
      name: copy file via ssh key
      runs-on: ubuntu-latest
      steps:
      uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: "home/zombie/rabi/test.tar"
          target: "home/rabi"